services:
  api:
    build: api-loopback-3/.
    ports:
      - "3000:3000"
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
    links:
      - mongodb
    depends_on:
      - mongodb
  web:
    build: web/.
    ports:
      - "80:80"
      - "443:443"
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
  mongodb:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure